### ISSUE TITLE
Camera, sound crashes  :error

### ISSUE THREAD

**Issue by XrTV** [PixelExperience-Devices/device_oneplus_dumpling#1]
Hi, on the latest version of PE 10+ edition, the camera is falling off. You always have to restart the device. Another problem with audio, especially in the popular Russian app Vkontakte, under some mythical circumstances, the sound disappears from the microphone. Even when calling from a SIM card. I also have to reload, and I will send the logcat later.

**Comment by itsjoeoui** [comment]
1. There is no such camera problem
2. Disable voice match, it's a known issue
